version: "3.8"

services:
  web:
    build:
      context: ./ecomsite
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecomsite:/code
    ports:
      - "8000:8000"
