# Generated by Django 5.0.6 on 2024-07-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeshop', '0003_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
