# Generated by Django 5.0.6 on 2024-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeshop', '0004_perfume_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
