# Generated by Django 4.1.3 on 2024-08-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeshop', '0005_alter_perfume_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_notes', models.TextField()),
                ('middle_notes', models.TextField()),
                ('base_notes', models.TextField()),
                ('fragrance_category', models.TextField()),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumeshop.perfume')),
            ],
        ),
    ]
