# Generated by Django 4.1.3 on 2024-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeshop', '0006_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='base_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='fragrance_category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='middle_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='top_notes',
            field=models.TextField(null=True),
        ),
    ]
